[package]
name = 'arcgisutils'
publish = false
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'arcgisutils'

[dependencies]
extendr-api = {version = '0.6.0', features = ["serde"] }
serde_esri = { version = "*" , git = "https://github.com/josiahparry/serde_esri", branch = "geom"}
serde_json = "1.0.108"

[patch.crates-io]
extendr-api = { git = "https://github.com/extendr/extendr"}

[profile.release]
lto = true
strip = true 