# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sfc_point_xy <- function(points) {
    .Call(`_arcgisutils_sfc_point_xy`, points)
}

sfc_point_xyz <- function(points) {
    .Call(`_arcgisutils_sfc_point_xyz`, points)
}

sfc_point_xyzm <- function(points) {
    .Call(`_arcgisutils_sfc_point_xyzm`, points)
}

sfc_point_impl <- function(points) {
    .Call(`_arcgisutils_sfc_point_impl`, points)
}

sfc_multipoint_impl <- function(mpoints) {
    .Call(`_arcgisutils_sfc_multipoint_impl`, mpoints)
}

sfc_linestring_impl <- function(mpoints) {
    .Call(`_arcgisutils_sfc_linestring_impl`, mpoints)
}

sfc_multilinestring_inner_impl <- function(mpoints) {
    .Call(`_arcgisutils_sfc_multilinestring_inner_impl`, mpoints)
}

sfc_multilinestring_impl <- function(mlines) {
    .Call(`_arcgisutils_sfc_multilinestring_impl`, mlines)
}

sfg_polygon_impl <- function(mply) {
    .Call(`_arcgisutils_sfg_polygon_impl`, mply)
}

sfc_polygon_impl <- function(mply) {
    .Call(`_arcgisutils_sfc_polygon_impl`, mply)
}

sfg_multipolygon_inner_impl <- function(mply) {
    .Call(`_arcgisutils_sfg_multipolygon_inner_impl`, mply)
}

sfg_multipolygon_impl <- function(mply) {
    .Call(`_arcgisutils_sfg_multipolygon_impl`, mply)
}

sfc_multipolygon_impl <- function(mply) {
    .Call(`_arcgisutils_sfc_multipolygon_impl`, mply)
}

transpose_impl <- function(x, names_template) {
    .Call(`_arcgisutils_transpose_impl`, x, names_template)
}

