# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples


on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}
          - {os: ubuntu-latest,   r: 'oldrel-2'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      NOT_CRAN: true

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src/rust

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            any::testthat
          needs: check
          dependencies: '"hard"'

      - name: Check R package
        id: rcmdcheck
        run: |
          options(crayon.enabled = TRUE)
          cat("LOGNAME=", Sys.info()[["user"]], "\n", sep = "", file = Sys.getenv("GITHUB_ENV"), append = TRUE)
          if (Sys.getenv("_R_CHECK_FORCE_SUGGESTS_", "") == "") Sys.setenv("_R_CHECK_FORCE_SUGGESTS_" = "false")
          if (Sys.getenv("_R_CHECK_CRAN_INCOMING_", "") == "") Sys.setenv("_R_CHECK_CRAN_INCOMING_" = "false")
          cat("check-dir-path=", file.path(getwd(), "check"), "\n", file = Sys.getenv("GITHUB_OUTPUT"), sep = "", append = TRUE)
          rcmdcheck::rcmdcheck(
            args = c("--no-manual", "--as-cran"),
            build_args = c("--no-manual", "--compact-vignettes=gs+qpdf"),
            error_on = "warning",
            check_dir = "check",
            env = c(NOT_CRAN = "true")
          )
        shell: Rscript {0}

      - name: Show testthat output
        if: always()
        run: |
          echo ::group::Show testthat output
          find check -name 'testthat.Rout*' -exec cat '{}' \; || true
          echo ::endgroup::
        shell: bash

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ format('{0}-{1}-r{2}-{3}-results', runner.os, runner.arch, matrix.config.r, strategy.job-index) }}
          path: ${{ steps.rcmdcheck.outputs.check-dir-path }}

      - name: Upload snapshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ format('{0}-{1}-r{2}-{3}-testthat-snapshots', runner.os, runner.arch, matrix.config.r, strategy.job-index) }}
          path: ${{ steps.rcmdcheck.outputs.check-dir-path }}/**/tests*/testthat/_snaps
          if-no-files-found: ignore

      - name: Show install log
        if: always()
        run: cat check/arcgisutils.Rcheck/00install.out

