# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples


on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}
          - {os: ubuntu-latest,   r: 'oldrel-2'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      NOT_CRAN: ${{ matrix.config.r != 'release' }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
          dependencies: '"hard"'

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'

  linux:
    # needs: [prepare, source]
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    name: Build R-${{ matrix.r }} for Linux
    strategy:
      fail-fast: false
      matrix:
        r: [ 'devel' ]
    container:
      image: ghcr.io/r-universe-org/base-image:${{ matrix.r }}
    steps:
      - name: Download source package
        uses: actions/download-artifact@v4
        with:
          name: package-source
          path: .
      - name: "Build and check binaries"
        uses: r-universe-org/actions/linux-check@v4
        id: build
        timeout-minutes: 60
        env:
          GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}